#!/usr/bin/env dart
// @license
// Copyright (c) 2026 ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:convert';
import 'dart:io';

import 'package:gg_console_colors/gg_console_colors.dart';

// .............................................................................
const dartEntry = 'lib/src/main.dart';
const generatedFolder = 'typescript/generated';
const wasmName = 'bridge-wasm';
const baseDnaFolder = '$generatedFolder/base-dna';

bool debug = false;
bool clean = false;

// .............................................................................
Future<void> main(List<String> args) async {
  debug = args.contains('--debug') || args.contains('-d');
  clean = args.contains('--clean');

  if (clean) {
    await _clean();
  }

  _ensurePrerequisites();
  _ensureGeneratedFolder();

  await _compileToWasm();
  await _wrapWasmIntoTypescript();
  await _syncBaseDna();

  print(green('Build complete.'));
}

// .............................................................................
String get _wasmBase => '$generatedFolder/$wasmName';

// .............................................................................
void _ensurePrerequisites() {
  if (!File(dartEntry).existsSync()) {
    stderr.writeln(red('Missing Dart entry point: $dartEntry'));
    exit(2);
  }
}

void _ensureGeneratedFolder() {
  final dir = Directory(generatedFolder);
  if (!dir.existsSync()) {
    dir.createSync(recursive: true);
  }
}

Future<void> _clean() async {
  final dir = Directory(generatedFolder);
  if (dir.existsSync()) {
    print(darkGray('Cleaning $generatedFolder ...'));
    await dir.delete(recursive: true);
  }
}

// .............................................................................
Future<void> _compileToWasm() async {
  final out = '$_wasmBase.wasm';
  await _run('Compiling $dartEntry → $out', [
    'dart',
    'compile',
    'wasm',
    dartEntry,
    '-o',
    out,
    debug ? '-O0' : '-O4',
    debug ? '--source-maps' : '--no-source-maps',
  ]);
}

Future<void> _wrapWasmIntoTypescript() async {
  final mjsFile = '$_wasmBase.mjs';
  final tsFile = '$_wasmBase.ts';

  print(darkGray('Wrapping $mjsFile → $tsFile'));

  final body = await File(mjsFile).readAsString();
  final wrapped = <String>[
    '// Generated by build.dart. Do not edit.',
    '// @ts-nocheck',
    '/* eslint-disable */',
    '',
    body,
    '',
  ].join('\n');

  await File(tsFile).writeAsString(wrapped);
  await File(mjsFile).delete();
}

// .............................................................................
// Bundle helix's own `dna/` folder — the implicit base layer of every
// instantiation — plus its version, next to the compiled wasm:
//
//   typescript/generated/base-dna/dna/**            (the base layer)
//   typescript/generated/base-dna/base-version.json ({"version": "5.0.0"})
//
// `pnpm run build:ts` copies the folder to `dist/base-dna` so the published
// package ships it. The runtime resolves it relative to the module URL.
Future<void> _syncBaseDna() async {
  final helixRoot = _resolveHelixRoot();
  final sourceDna = Directory('$helixRoot/dna');
  if (!sourceDna.existsSync()) {
    stderr.writeln(red('helix package has no dna/ folder: $helixRoot'));
    exit(2);
  }

  // The agent skills are the part of the base DNA most easily lost: a
  // helix that keeps them at `dna/.claude/` instead of the escaped
  // `dna/dot-claude/` loses them on `dart pub publish`, which drops every
  // path with a leading dot — so the bundle would silently carry a base
  // DNA without any skills. Fail loudly on that unpublishable layout.
  // A helix whose `dna/` carries no skills folder at all is fine: since
  // the rename the engine ships only the DNA config there.
  if (Directory('$helixRoot/dna/.claude').existsSync()) {
    stderr.writeln(red(
      'helix at $helixRoot keeps its agent skills at dna/.claude — the '
      'leading dot is dropped on publish, so they would be missing from '
      'the bundle. It must use the escaped dna/dot-claude layout.',
    ));
    exit(2);
  }

  final target = Directory(baseDnaFolder);
  if (target.existsSync()) {
    target.deleteSync(recursive: true);
  }
  target.createSync(recursive: true);

  print(darkGray('Copying $helixRoot/dna → $baseDnaFolder/dna'));
  _copyTree(sourceDna, Directory('$baseDnaFolder/dna'));

  final version = _helixVersion(helixRoot);
  final versionFile = File('$baseDnaFolder/base-version.json');
  versionFile.writeAsStringSync(
    '${const JsonEncoder.withIndent('  ').convert({'version': version})}\n',
  );
  print(darkGray('Base DNA version: $version'));
}

// Resolves the root folder of the helix dependency from
// .dart_tool/package_config.json — works for path and hosted dependencies.
String _resolveHelixRoot() {
  final configFile = File('.dart_tool/package_config.json');
  if (!configFile.existsSync()) {
    stderr.writeln(red('Missing .dart_tool/package_config.json — '
        'run `dart pub get` first.'));
    exit(2);
  }
  final doc =
      jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
  for (final pkg in (doc['packages'] as List?) ?? const <Object?>[]) {
    if (pkg is! Map<String, dynamic>) continue;
    if (pkg['name'] != 'helix') continue;
    final rootUri = Uri.parse(pkg['rootUri'] as String);
    final resolved = configFile.absolute.uri.resolveUri(rootUri);
    final path = resolved.toFilePath();
    return path.endsWith(Platform.pathSeparator)
        ? path.substring(0, path.length - 1)
        : path;
  }
  stderr.writeln(red('helix not found in package_config.json.'));
  exit(2);
}

String _helixVersion(String helixRoot) {
  final pubspec = File('$helixRoot/pubspec.yaml').readAsStringSync();
  final match =
      RegExp(r'^version:\s*(\S+)', multiLine: true).firstMatch(pubspec);
  if (match == null) {
    stderr.writeln(red('No version: line in $helixRoot/pubspec.yaml.'));
    exit(2);
  }
  return match.group(1)!;
}

void _copyTree(Directory from, Directory to) {
  to.createSync(recursive: true);
  for (final entity in from.listSync(recursive: true, followLinks: false)) {
    final rel = entity.path.substring(from.path.length + 1);
    if (entity is Directory) {
      Directory('${to.path}/$rel').createSync(recursive: true);
    } else if (entity is File) {
      final target = File('${to.path}/$rel');
      target.parent.createSync(recursive: true);
      entity.copySync(target.path);
    }
  }
}

// .............................................................................
Future<void> _run(String description, List<String> command) async {
  print(yellow(description));
  final p = await Process.start(
    command.first,
    command.sublist(1),
    mode: ProcessStartMode.inheritStdio,
  );
  final code = await p.exitCode;
  if (code != 0) {
    stderr.writeln(red('Command failed (exit $code): ${command.join(' ')}'));
    exit(code);
  }
}
