// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/gg_dna_js_version.test.ts.

/** The version of the `@tssuite/gg_dna-js` package. */
export const ggDnaJsVersion = '1.0.1';
